# -*- coding: utf-8 -*-
"""Game.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/14_82NzZYrHISpKdho-8cmk5UvxC_p592
"""

import random

class Game:
    """Classe représentant un jeu de Pierre-Feuille-Ciseaux."""

    def __init__(self):
        """Constructeur de la classe Game"""
        self.choices = ["rock", "paper", "scissors"]

    def get_user_item(self):
        while True:
            print("Choisissez votre arme :")
            print("   • rock (pierre)     → tapez 'rock'")
            print("   • paper (feuille)   → tapez  'paper'")
            print("   • scissors (ciseaux) → tapez  'scissors'")

            user_input = input("\nVotre choix : ").strip().lower()

            # Vérification si l'utilisateur a tapé le mot complet
            if user_input in self.choices:
                print(f"\nVous avez choisi : {user_input.upper()} !")
                return user_input

            # Si le choix est invalide
            print("\nChoix invalide ! Veuillez choisir parmi : rock, paper, scissors")

    def get_computer_item(self):
        computer_choice = random.choice(self.choices)
        print(f"\nL'ordinateur a choisi : {computer_choice.upper()} !")
        return computer_choice

    def get_game_result(self, user_item, computer_item):

        # Règles du jeu
        rules = {
            ("rock", "scissors"): "win",
            ("scissors", "paper"): "win",
            ("paper", "rock"): "win",
            ("rock", "paper"): "loss",
            ("paper", "scissors"): "loss",
            ("scissors", "rock"): "loss"
        }

        # Égalité
        if user_item == computer_item:
            return "draw"

        # Victoire ou défaite
        return rules[(user_item, computer_item)]

    def play(self):

        # Étape 1 : Obtenir le choix de l'utilisateur
        user_item = self.get_user_item()

        # Étape 2 : Obtenir le choix de l'ordinateur
        computer_item = self.get_computer_item()

        # Étape 3 : Déterminer le résultat
        result = self.get_game_result(user_item, computer_item)

        # Étape 4 : Afficher le résultat de manière conviviale

        # messages selon le résultat
        if result == "win":
            print(f"VOUS AVEZ GAGNÉ !")
            print(f"   {user_item} bat {computer_item} → Félicitations !")
        elif result == "loss":
            print(f"VOUS AVEZ PERDU ! ")
            print(f"   {computer_item} bat {user_item} → Meilleure chance la prochaine fois !")
        else:
            print(f"ÉGALITÉ !")
            print(f"   Vous avez tous les deux choisi {user_item} → Match nul !")


        return result