# -*- coding: utf-8 -*-
"""rock-paper-scissors.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Ju4z26ofYRR_ONbXbDVzd2FNByE0yuul
"""

from game import Game

def get_user_menu_choice():
    print("MENU PRINCIPAL")
    print("=" * 50)
    print("1. Jouer une nouvelle partie")
    print("2. Voir les scores")
    print("3. Quitter")

    while True:
        choice = input("\nQue voulez-vous faire ? (1/2/3) : ").strip()
        if choice in ['1', '2', '3']:
            return choice
        else:
            print("Choix invalide ! Veuillez entrer 1, 2 ou 3.")

def print_results(results):

    print("STATISTIQUES FINALES ")
    print("=" * 50)

    total_games = sum(results.values())

    # Affichage des résultats avec emojis
    print(f"\nNombre total de parties : {total_games}")
    print("DÉTAIL DES RÉSULTATS :")

    print(f"Victoires   : {results['win']}")
    print(f"Défaites    : {results['loss']}")
    print(f"Égalités    : {results['draw']}")

def main():
    print("   BIENVENUE DANS LE JEU PIERRE-FEUILLE-CISEAUX !   ")

    # Initialisation du dictionnaire des résultats
    results = {
        'win': 0,
        'loss': 0,
        'draw': 0
    }

    # Boucle principale du jeu
    while True:
        choice = get_user_menu_choice()

        if choice == '1':  # Jouer une nouvelle partie

            print("   LANCEMENT D'UNE NOUVELLE PARTIE   ")


            # Création et exécution d'une partie
            game = Game()
            game_result = game.play()

            # Mise à jour des statistiques
            results[game_result] += 1

            # Message de confirmation
            result_fr = {
                'win': 'gagné ',
                'loss': 'perdu ',
                'draw': 'fait match nul '
            }
            print(f"\nPartie enregistrée : VOUS AVEZ {result_fr[game_result].upper()} !")

        elif choice == '2':  # Voir les scores
            print("\nAFFICHAGE DES SCORES ACTUELS")
            total = sum(results.values())
            if total == 0:
                print("\nAucune partie n'a encore été jouée.")
                print("Jouez d'abord une partie pour voir vos scores !")
            else:
                print(f"\nStatistiques depuis le début de la session :")
                print(f"   • Victoires : {results['win']}")
                print(f"   • Défaites  : {results['loss']}")
                print(f"   • Égalités  : {results['draw']}")
                print(f"   • Total     : {total}")


        elif choice == '3':  # Quitter
            print("\nFERMETURE DU PROGRAMME... ")
            # Affichage du résumé final avant de quitter
            print_results(results)
            break

    print("\nAu revoir et à bientôt pour de nouvelles parties !")

# Point d'entrée du programme
if __name__ == "__main__":
    main()